manifest:
  remotes:
    - name: Piotrryt
      url-base: https://github.com/Piotrryt
  projects:
    - name: zmk
      remote: Piotrryt
      revision: main
      import: app/west.yml
  self:
    path: config
